[package]
name = "izuna"
version = "0.1.0"
edition = "2021"

[dependencies]
fern = "0.7.1"
log = "0.4.27"

[dependencies.windows]
version = "0.61.1"
features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]

[[bin]]
name = "izuna"
path = "src/main.rs"
